# Generated by Django 3.2.7 on 2021-09-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidersCacheDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_date', models.DateTimeField(verbose_name='Last date for getting providers')),
                ('providers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_providers.providers', unique=True)),
            ],
        ),
    ]
